# Generated by Django 5.1.5 on 2025-01-28 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apis.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_rename_location_church_address_church_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(default=apis.models.Application.generate_application_id, max_length=15, unique=True)),
                ('avg_service_attendance', models.IntegerField(default=0)),
                ('avg_monthly_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('avg_monthly_contributions', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('avg_monthly_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('available_funds_for_project', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('support_type', models.CharField(choices=[('AID', 'AID'), ('REVOLVING_FUND', 'REVOLVING_FUND')], default='AID', max_length=20)),
                ('type_of_church_project', models.CharField(choices=[('REGIONAL HEADQUARTERS CHURCH', 'REGIONAL HEADQUARTERS CHURCH'), ('DIVISIONAL HEADQUARTERS CHURCH', 'DIVISIONAL HEADQUARTERS CHURCH'), ('GROUP OF DISTRICTS HEADQUARTERS CHURCH', 'GROUP OF DISTRICTS HEADQUARTERS CHURCH'), ('DISTRICT CHURCH', 'DISTRICT CHURCH'), ('LOCATION CHURCH', 'LOCATION CHURCH')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('amount_in_words', models.CharField(default='', max_length=500)),
                ('estimated_project_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('project_location', models.CharField(max_length=500)),
                ('purpose', models.TextField()),
                ('phase', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.church')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
