# Generated by Django 5.1.5 on 2025-01-29 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apis.models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_alter_application_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disbursement_id', models.CharField(default=apis.models.Disbursement.generate_disbursement_id, max_length=15, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('payment_reference', models.CharField(default='', max_length=50)),
                ('date_paid', models.DateField()),
                ('proof_of_payment', models.FileField(upload_to='disbursments/')),
                ('status', models.CharField(default='PENDING REVIEW', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apis.application')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
