# Generated by Django 5.1.5 on 2025-01-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='schedule_start_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
