# Generated by Django 5.1.5 on 2025-01-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_notification_schedule_start_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
