# Generated by Django 5.1.5 on 2025-03-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_application_cost_estimate_application_current_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='activity_completed',
            field=models.BooleanField(default=False),
        ),
    ]
