# Generated by Django 5.1.5 on 2025-04-02 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_repayment_updated_by_alter_repayment_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PENDING REVIEW', 'PENDING REVIEW'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('UNDER REVIEW', 'UNDER REVIEW'), ("WAITING NO'S APPROVAL", "WAITING NO'S APPROVAL")], default='DRAFT', max_length=25),
        ),
    ]
