# Generated by Django 5.1.5 on 2025-04-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0016_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressreport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('VERIFIED', 'VERIFIED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=15),
        ),
    ]
