# Generated by Django 5.1.5 on 2025-04-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0017_alter_progressreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='notifications/'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target',
            field=models.CharField(choices=[('CHURCH', 'CHURCH'), ('DISTRICT', 'DISTRICT'), ('REGION', 'REGION'), ('ALL', 'ALL')], default='ALL', max_length=20),
        ),
    ]
