# Generated by Django 5.1.5 on 2025-06-24 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0018_notification_attachment_notification_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='award_reference',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
