# Generated by Django 5.1.5 on 2025-06-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0019_application_award_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='monthly_repayment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
