# Generated by Django 5.1.5 on 2025-06-24 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0020_application_monthly_repayment_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='purpose',
            new_name='justification_for_aid',
        ),
        migrations.RemoveField(
            model_name='application',
            name='description',
        ),
    ]
