# Generated by Django 5.1.5 on 2025-01-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='CHURCH_USER', max_length=20),
        ),
    ]
