# Generated by Django 5.1.5 on 2025-02-05 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_region_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='church',
            name='region',
        ),
    ]
