# Generated by Django 5.1.5 on 2025-03-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_church_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='church_type',
            field=models.CharField(default='LOCATION', max_length=20),
        ),
    ]
