# Generated by Django 5.1.5 on 2025-06-24 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_region_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='church',
            old_name='address',
            new_name='location_address',
        ),
        migrations.RenameField(
            model_name='church',
            old_name='name',
            new_name='location_name',
        ),
        migrations.RemoveField(
            model_name='church',
            name='church_type',
        ),
        migrations.AddField(
            model_name='church',
            name='church_status',
            field=models.CharField(default='Location Church', max_length=20),
        ),
        migrations.AddField(
            model_name='church',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.region'),
        ),
        migrations.AlterField(
            model_name='church',
            name='church_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='pastor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
