# Generated by Django 5.1.5 on 2025-06-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_address_church_location_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='manager_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='church',
            name='manager_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='church',
            name='manager_phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
