# Generated by Django 5.1.5 on 2025-06-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_church_manager_email_church_manager_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='church_status',
            field=models.CharField(default='Location Church', max_length=60),
        ),
    ]
